name: ReqRes.in API testing

on:
 workflow_dispatch:

jobs:
 build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install htmlextra
        run: npm install -g newman-reporter-htmlextra

      - name: Run a one-line script
        run: newman run 'REQRES.IN APIs ITI Project.postman_collection.json'

      - uses: actions/upload-artifact@v2
        with: 
           name: newman-reports
           path: ./newman
