name: ReqRes.in API testing

on:
 workflow_dispatch:

jobs:
 build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Newman and htmlextra
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run Newman with HTML Extra Reporter
        run: newman run 'REQRES.IN APIs ITI Project.postman_collection.json' -r htmlextra --reporter-htmlextra-export './newman/report.html'

      - uses: actions/upload-artifact@v2
        with: 
           name: newman-reports
           path: ./newman/*
